feat(install): modify python repo with longcolumn branch

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -91,7 +91,7 @@ def sync_source() {
                 if [ ! -d src/connector/python/.github ]; then
                     rm -rf src/connector/python/* || :
                     rm -rf src/connector/python/.* || :
-                    git clone --depth 1 https://github.com/taosdata/taos-connector-python src/connector/python || echo "failed to clone python connector"
+                    git clone -b longcolumn --depth 1 https://github.com/taosdata/taos-connector-python src/connector/python || echo "failed to clone python connector"
                 else
                     cd src/connector/python || echo "src/connector/python not exist"
                     git pull || :
@@ -108,7 +108,7 @@ def sync_source() {
                 if [ ! -d community/src/connector/python/.github ]; then
                     rm -rf community/src/connector/python/* || :
                     rm -rf community/src/connector/python/.* || :
-                    git clone --depth 1 https://github.com/taosdata/taos-connector-python community/src/connector/python || echo "failed to clone python connector"
+                    git clone -b longcolumn --depth 1 https://github.com/taosdata/taos-connector-python community/src/connector/python || echo "failed to clone python connector"
                 else
                     cd community/src/connector/python || echo "community/src/connector/python not exist"
                     git pull || :
