[TD-14358]<fix>: remove python connector from TDengine (#11066)
* [TD-14358]<fix>: remove python connector from TDengine

* [TD-14358]<fix>: use standalone python connector

* add python clone in TDinternal

* git clean before checkout

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -36,6 +36,7 @@ def sync_source() {
         } else {
             sh '''
                 cd ${WKC}
+                git clean -fxd
                 git checkout develop
             '''
         }
@@ -83,6 +84,16 @@ def sync_source() {
                 cd ${WKC}
                 git fetch origin +refs/pull/${CHANGE_ID}/merge
                 git checkout -qf FETCH_HEAD
+
+                if [ ! -d src/connector/python/.github ]; then
+                    rm -rf src/connector/python/* || :
+                    rm -rf src/connector/python/.* || :
+                    git clone --depth 1 https://github.com/taosdata/taos-connector-python src/connector/python || echo "failed to clone python connector"
+                else
+                    cd src/connector/python || echo "src/connector/python not exist"
+                    git pull || :
+                    cd ${WKC}
+                fi
             '''
         } else if (env.CHANGE_URL =~ /\/TDinternal\//) {
             sh '''
@@ -90,6 +101,16 @@ def sync_source() {
                 cd ${WK}
                 git fetch origin +refs/pull/${CHANGE_ID}/merge
                 git checkout -qf FETCH_HEAD
+
+                if [ ! -d community/src/connector/python/.github ]; then
+                    rm -rf community/src/connector/python/* || :
+                    rm -rf community/src/connector/python/.* || :
+                    git clone --depth 1 https://github.com/taosdata/taos-connector-python community/src/connector/python || echo "failed to clone python connector"
+                else
+                    cd community/src/connector/python || echo "community/src/connector/python not exist"
+                    git pull || :
+                    cd ${WK}
+                fi
             '''
         } else {
             sh '''
