[TD-14358]<fix>: use standalone python connector

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -83,6 +83,16 @@ def sync_source() {
                 cd ${WKC}
                 git fetch origin +refs/pull/${CHANGE_ID}/merge
                 git checkout -qf FETCH_HEAD
+
+                if [ -d src/connector/python/.git ]; then
+                    rm -rf src/connector/python/* || :
+                    rm -rf src/connector/python/.* || :
+                    git clone --depth 1 https://github.com/taosdata/taos-connector-python src/connector/python || echo "failed to clone python connector"
+                else
+                    cd src/connector/python || echo "src/connector/python not exist"
+                    git pull || :
+                    cd ${WKC}
+                fi
             '''
         } else if (env.CHANGE_URL =~ /\/TDinternal\//) {
             sh '''
