feat(pulsar): support pulsar and pulsar-tuya data source (#3378)
* feat(pulsar): support pulsar and pulsar-tuya data source

Closes [TS-7448](https://jira.taosdata.com:18080/browse/TS-7448)

* chore: and and depends on install-protoc for taosx/agent

* chore: fix clippy error

* chore: install protoc in docker dev image [ci skip]

* fix(legacy): fix 0x2602 invalid column name vgroup_id when use stables in cloud

```bash
taosx run\
  -f "taos+https://gw.us-central-1.gcp.cloud.tdengine.com/prod?token=xxx&schema=only&stables=windspeeds,trackers,snowdepths" \
  -t taos:///prod
```

Error: [0x2602] Internal error: `Invalid column name: vgroup_id`

Caused by:
    Internal error: `Invalid column name: vgroup_id`

---------

Co-authored-by: Linhe Huo <linhehuo@gmail.com>

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -1,75 +1,79 @@
 # command "toml get ..." requires installation of "toml-cli" first, ref https://github.com/gnprice/toml-cli
 
 # Use env scripts to get the latest version from git tags to make it available for any platform.
-env_scripts = ['''
-  #!@duckscript
+env_scripts = [
+  '''
+    #!@duckscript
 
-  # setup version
-  ver = get_env VER_NUMBER
-  if is_empty ${ver}
-    out = exec git describe --tags --abbrev=0
-    ver = trim ${out.stdout}
-    ver = replace ${ver} "ver-" ""
-    echo "* last published version: ${ver}"
-    set_env "VER_NUMBER" "${ver}"
-  end
-
-  # 获取编译器版本信息
-  gcc_version = exec cc -dumpversion
-  version = trim ${gcc_version.stdout}
-  if is_empty ${version}
-    set_env "CFLAGS" "-fno-builtin"
-  else
-    echo "GCC version: ${version}"
-
-    if contains ${version} "."
-      version = semver_parse "${version}"
-    else
-      version = semver_parse "${version}.0.0"
+    # setup version
+    ver = get_env VER_NUMBER
+    if is_empty ${ver}
+      out = exec git describe --tags --abbrev=0
+      ver = trim ${out.stdout}
+      ver = replace ${ver} "ver-" ""
+      echo "* last published version: ${ver}"
+      set_env "VER_NUMBER" "${ver}"
     end
-    echo "Major version: ${version.major}"
 
-    # 比较主版本号是否大于 9
-    if greater_than ${version.major} 9
-        echo "GCC version is 10+"
+    # 获取编译器版本信息
+    gcc_version = exec cc -dumpversion
+    version = trim ${gcc_version.stdout}
+    if is_empty ${version}
+      set_env "CFLAGS" "-fno-builtin"
     else
-        echo "GCC version is 9 or lower, use -fno-builtin"
-        set_env "CFLAGS" "-fno-builtin"
+      echo "GCC version: ${version}"
+
+      if contains ${version} "."
+        version = semver_parse "${version}"
+      else
+        version = semver_parse "${version}.0.0"
+      end
+      echo "Major version: ${version.major}"
+
+      # 比较主版本号是否大于 9
+      if greater_than ${version.major} 9
+          echo "GCC version is 10+"
+      else
+          echo "GCC version is 9 or lower, use -fno-builtin"
+          set_env "CFLAGS" "-fno-builtin"
+      end
     end
-  end
 
-  cus_name = get_env "CUS_NAME"
-  echo ${cus_name}
-  if is_empty "${cus_name}"
-    cus_name = set "TDengine"
-    set_env "CUS_NAME" "${cus_name}"
-  end
-  echo "Product: ${cus_name}"
-
-  if eq "${cus_name}" "TDengine TSDB-Lite"
-    set_env "TSDB_LITE" "true"
-  end
-
-  cus_prompt = get_env "CUS_PROMPT"
-  if is_empty "${cus_prompt}"
-    cus_prompt = set "taos"
-    set_env "CUS_PROMPT" "${cus_prompt}"
-  end
-  echo "Prompt: ${cus_prompt}"
-
-  # 获取插件目录
-  plugins_home = get_env "PLUGINS_HOME"
-
-  # 获取当前系统平台
-  os = os_family
-  if is_empty "${plugins_home}"
-    if eq ${os} "windows"
-      set_env "PLUGINS_HOME" "C:\\${cus_name}\\plugins"
-    else
-      set_env "PLUGINS_HOME" "/usr/local/${cus_prompt}/plugins"
+    cus_name = get_env "CUS_NAME"
+    echo ${cus_name}
+    if is_empty "${cus_name}"
+      cus_name = set "TDengine"
+      set_env "CUS_NAME" "${cus_name}"
     end
-  end
-  ''']
+    echo "Product: ${cus_name}"
+
+    if eq "${cus_name}" "TDengine TSDB-Lite"
+      set_env "TSDB_LITE" "true"
+    end
+
+    cus_prompt = get_env "CUS_PROMPT"
+    if is_empty "${cus_prompt}"
+      cus_prompt = set "taos"
+      set_env "CUS_PROMPT" "${cus_prompt}"
+    end
+    echo "Prompt: ${cus_prompt}"
+
+    # 获取插件目录
+    plugins_home = get_env "PLUGINS_HOME"
+
+    # 获取当前系统平台
+    os = os_family
+    echo "Build on OS: ${os}"
+    set_env "CARGO_MAKE_BUILD_OS_FAMILY" "${os}"
+    if is_empty "${plugins_home}"
+      if eq ${os} "windows"
+        set_env "PLUGINS_HOME" "C:\\${cus_name}\\plugins"
+      else
+        set_env "PLUGINS_HOME" "/usr/local/${cus_prompt}/plugins"
+      end
+    end
+    ''',
+]
 
 [config]
 load_cargo_aliases = false
@@ -78,9 +82,7 @@ default_to_workspace = false
 
 [env]
 UPX_DIR = "./target/deploy/upx/"
-BUILD_PROFILE = { value = "release", condition = { env_not_set = [
-  "BUILD_PROFILE",
-] } }
+BUILD_PROFILE = { value = "release", condition = { env_not_set = ["BUILD_PROFILE"] } }
 RUST_VERSION = "1.90.0"
 ZIG_VERSION = "0.14.1"
 
@@ -95,18 +97,23 @@ echo BUILD_PROFILE=$BUILD_PROFILE
 echo CFLAGS=$CFLAGS
 echo PLUGINS_HOME=$PLUGINS_HOME
 """
+[tasks.taosx-unlicensed]
+condition.files_modified = { input = ["${CARGO_MAKE_WORKING_DIRECTORY}/**/Cargo.*", "src/**/*.rs", "crates/**/*.rs", "taosx-core/src/**/*.rs", "taosx-ipc/src/**/*.rs", "taosx-metrics/src/**/*.rs"], output = ["target/${BUILD_PROFILE}/taosx"] }
+dependencies = ["install-protoc"]
+command = "cargo"
+args = [
+  "build",
+  "-p",
+  "taosx",
+  "--features",
+  "disable-enterprise-only-validation,disable-enterprise-connector-validation",
+  "--profile",
+  "${BUILD_PROFILE}",
+]
 
 [tasks.taosx]
-condition.files_modified = { input = [
-  "${CARGO_MAKE_WORKING_DIRECTORY}/**/Cargo.*",
-  "src/**/*.rs",
-  "crates/**/*.rs",
-  "taosx-core/src/**/*.rs",
-  "taosx-ipc/src/**/*.rs",
-  "taosx-metrics/src/**/*.rs",
-], output = [
-  "target/${BUILD_PROFILE}/taosx",
-] }
+condition.files_modified = { input = ["${CARGO_MAKE_WORKING_DIRECTORY}/**/Cargo.*", "src/**/*.rs", "crates/**/*.rs", "taosx-core/src/**/*.rs", "taosx-ipc/src/**/*.rs", "taosx-metrics/src/**/*.rs"], output = ["target/${BUILD_PROFILE}/taosx"] }
+dependencies = ["install-protoc"]
 command = "cargo"
 args = ["build", "-p", "taosx", "--profile", "${BUILD_PROFILE}"]
 
@@ -125,6 +132,7 @@ args = [
 
 [tasks.taosx-agent]
 command = "cargo"
+dependencies = ["install-protoc"]
 args = ["build", "--profile", "${BUILD_PROFILE}", "-p", "taosx-agent"]
 
 [tasks.plugins]
@@ -206,12 +214,7 @@ deprecated = true
 
 [tasks.install-plugins]
 description = "Install all available plugins"
-run_task = { name = [
-  "install-plugin-opc",
-  "install-plugin-influxdb",
-  "install-plugin-opentsdb",
-] }
-
+run_task = { name = ["install-plugin-opc", "install-plugin-influxdb", "install-plugin-opentsdb"] }
 
 [tasks.install-plugin-opc]
 condition = { files_exist = ["plugins/opc/taosx-opc"] }
@@ -363,7 +366,7 @@ rm -rf ./TDengine-enterprise-client-${VER_NUMBER}
 """
 dependencies = [
   "taosx",
-  #"taos-explorer",
+  # "taos-explorer",
   "plugins",
 ]
 
@@ -438,9 +441,10 @@ rm -rf ./docker/integrated/release
 rm -rf ./TDengine-enterprise-${VER_NUMBER}
 """
 dependencies = [
-  #"taosx",
-  #"plugins",
-  #"taos-explorer"
+
+  # "taosx",
+  # "plugins",
+  # "taos-explorer"
 ]
 
 [tasks.verify-integrated-image]
@@ -783,11 +787,12 @@ docker run --rm -v .:/app -w /app \
 """
 
 [tasks.fmt]
+dependencies = ["assert-explorer-dist", "install-protoc"]
 command = "cargo"
 args = ["fmt", "--check", "--all"]
 
 [tasks.clippy]
-dependencies = ["assert-explorer-dist"]
+dependencies = ["assert-explorer-dist", "install-protoc"]
 command = "cargo"
 args = [
   "clippy",
@@ -857,16 +862,7 @@ rm -rf explorer/public/docs-en
 """
 [tasks.explorer-ui-prod]
 dependencies = ["download-docs-from-remote", "remove-docs-if-community"]
-condition.files_modified = { input = [
-  "explorer/package.json",
-  "explorer/vite.config.ts",
-  "explorer/pnpm-*.yaml",
-  "explorer/src/**",
-  "explorer/static/**",
-  "explorer/taos-ui/**",
-], output = [
-  "explorer/dist/",
-] }
+condition.files_modified = { input = ["explorer/package.json", "explorer/vite.config.ts", "explorer/pnpm-*.yaml", "explorer/src/**", "explorer/static/**", "explorer/taos-ui/**"], output = ["explorer/dist/"] }
 condition.env_not_set = ["NO_BUILD_UI"]
 cwd = "explorer"
 script_runner = "@duckscript"
@@ -911,12 +907,9 @@ dependencies = ["explorer-ui-prod"]
 command = "cargo"
 args = ["build", "-p", "taos-explorer", "--profile", "${BUILD_PROFILE}"]
 
-
 [tasks.explorer]
 run_task = [
-  { name = "explorer-disable-x-api", condition = { env_true = [
-    "TSDB_LITE",
-  ] } },
+  { name = "explorer-disable-x-api", condition = { env_true = ["TSDB_LITE"] } },
   { name = "explorer-with-x-api" },
 ]
 
@@ -967,6 +960,95 @@ install_crate = { crate_name = "cargo-llvm-cov", binary = "cargo-llvm-cov", rust
 install_crate = { crate_name = "cargo-nextest", binary = "cargo-nextest", test_arg = "--version" }
 [tasks.install-toml-cli]
 install_crate = { crate_name = "toml-cli", binary = "toml", test_arg = "--version" }
+[tasks.install-protoc]
+script_runner = "@duckscript"
+install_script = """
+# 设置 protoc 版本和下载 URL
+protoc_version = set "33.0"
+protoc_url_prefix = set "https://github.com/protocolbuffers/protobuf/releases/download/v${protoc_version}"
+
+protoc_cmd = which protoc
+if is_empty ${protoc_cmd}
+  echo "Install protoc v${protoc_version}"
+else
+  installed_version = exec protoc --version
+  echo "Protoc has been installed: ${installed_version.stdout}"
+  exit
+end
+
+family = os_family
+
+if equals ${family} "windows"
+  file = set "protobuf-${protoc_version}.zip"
+elseif equals ${family} "mac"
+  file = set "protoc-${protoc_version}-osx-aarch_64.zip"
+else
+  apt_exe = which apt-get
+  if is_empty ${apt_exe}
+  else
+    code = exec --get-exit-code sudo apt-get install protobuf-compiler
+    if equals ${code} 0
+      installed_version = exec protoc --version
+      echo successfully installed.. ${installed_version}
+      exit
+    end
+  end
+
+  arch = get_env "CARGO_MAKE_RUST_TARGET_ARCH"
+  echo "Build arch: " ${arch}
+  if equals "${arch}" "x86_64"
+    file = set "protoc-${protoc_version}-linux-x86_64.zip"
+  elseif equals ${arch} "aarch64"
+    file = set "protoc-${protoc_version}-linux-aarch_64.zip"
+  elseif equals ${arch} "s390"
+    file = set "protoc-${protoc_version}-linux-s390_64.zip"
+  elseif equals ${arch} "powerpc64le"
+    file = set "protoc-${protoc_version}-linux-ppcle_64.zip"
+  else
+    echo "Unsupported architecture: ${arch}"
+    exit 1
+  end
+end
+
+download_url = set "${protoc_url_prefix}/${file}"
+
+echo "Downloading: ${download_url}"
+
+size = wget -O ${file} ${download_url}
+
+install_path = get_env "CARGO_HOME"
+
+unzip_exe = which unzip
+if is_empty ${unzip_exe}
+  echo "Guess you're using windows"
+  exec powershell -command "Expand-Archive -Force '${file}' '${install_path}/'"
+else
+  output = exec unzip -o "${file}" -d ${install_path}
+  stdout = set ${output.stdout}
+  stderr = set ${output.stderr}
+  exit_code = set ${output.code}
+
+  if equals ${exit_code} 0
+    echo "Stdout:"
+    echo ${stdout}
+  else
+    echo "Stderr:"
+    echo ${stderr}
+  end
+end
+
+protoc_file = join_path "${install_path}" bin protoc
+echo "Installed at: " ${protoc_file}
+chmod 770 ${protoc_file}
+
+protoc_expect = which protoc
+if is_empty "${protoc_expect}"
+  echo "Error: Protoc installation failed: protoc file not found in ${install_path}"
+  exit 1
+end
+echo "Installed proto compiler (protoc)"
+rm ${file}
+"""
 [tasks.install-nvm]
 windows_alias = "empty"
 install_script = """
