change td cluster check

diff --git a/enterprise/packaging/docker/2.x-files/td_cluster_check b/enterprise/packaging/docker/2.x-files/td_cluster_check
--- a/enterprise/packaging/docker/2.x-files/td_cluster_check
+++ b/enterprise/packaging/docker/2.x-files/td_cluster_check
@@ -23,17 +23,20 @@ logging "INFO" "TAOS_TIMEOUT_SECOND: ${TAOS_TIMEOUT_SECOND}"
 logging "INFO" "FIRST_EP_HOST: ${FIRST_EP_HOST}"
 logging "INFO" "FIRST_EP_PORT: ${FIRST_EP_PORT}"
 logging "INFO" "ENDPOINT: ${ENDPOINT}"
+NotCheckTaosadapter=$1
+if [ -z $NotCheckTaosadapter ]; then
+    nc -z 127.0.0.1 6041
+    if [ $? -ne 0 ]; then
+        logging "ERROR" "taosadapter port 6041 is not ok"
+        exit 1
+    fi
+fi
 
-# nc -z 127.0.0.1 6041
-# if [ $? -ne 0 ]; then
-#     logging "INFO" "taosadapter port 6041 is not ok"
-#     exit 1
-# fi
 
 # get dnode id
 DNODETmp=$(timeout $TAOS_TIMEOUT_SECOND taos -h $FIRST_EP_HOST -P $FIRST_EP_PORT -w 2000 -s "show dnodes;" | grep -E "$ENDPOINT" | awk '{split($0,a,"|");print a[1]}' | awk '{gsub(/ /,"")}1' )
 if [[ "$DNODETmp" == "" ]]; then
-    logging "INFO" "Could not get dnode number"
+    logging "ERROR" "Could not get dnode number"
     exit 1
 fi
 logging "INFO" "DNODETmp $DNODETmp"
@@ -45,7 +48,7 @@ if [[ "$VGroupStatusTmp" == "" ]]; then
     logging "INFO" "All vgroup is ready!!"
     exit 0
 else 
-    logger "INFO" "there is vgroup not ready ！！ $VGroupStatusTmp"
+    logger "ERROR" "there is vgroup not ready ！！ $VGroupStatusTmp"
     exit 1
 fi
 
